"""Execution-time, feedback, and evaluation schemas."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import Field, PositiveInt, model_validator

from .base import Identifier, NonEmptyStr, StrictSchema, utc_now
from .enums import ArtifactRole, AttemptStatus, EvaluationDecision, EvaluationStatus, FailureType, NodeKind, ReplanScope
from .plan import SlotSpec, SuccessCriteria


class ArtifactBinding(StrictSchema):
    """Runtime binding between a logical slot and a concrete artifact id."""

    spec_name: NonEmptyStr = Field(description="Slot name from the plan.")
    role: ArtifactRole = Field(description="Semantic role copied from the slot.")
    artifact_id: Identifier = Field(description="Concrete artifact id bound to the slot.")


class NamedScore(StrictSchema):
    """Named evaluator score represented as a list item for structured-output compatibility."""

    name: NonEmptyStr = Field(description="Score dimension name, such as fidelity or naturalness.")
    value: float = Field(description="Score value in the inclusive range [0, 1].")

    @model_validator(mode="after")
    def validate_score(self) -> "NamedScore":
        if not 0.0 <= self.value <= 1.0:
            raise ValueError("score value must be within [0, 1]")
        return self


class HardRuleResult(StrictSchema):
    """One hard-rule evaluation result."""

    rule: NonEmptyStr = Field(description="Hard rule text that was evaluated.")
    passed: bool = Field(description="Whether the hard rule passed.")


class RetryAdvice(StrictSchema):
    """Tactical retry guidance generated by the evaluator."""

    advice_id: Identifier = Field(description="Unique identifier for this retry advice object.")
    error_diagnostic: NonEmptyStr = Field(description="What went wrong in the previous attempt.")
    suggested_prompts: list[NonEmptyStr] = Field(
        default_factory=list,
        description="Prompt rewrites or additions recommended for retry.",
    )
    avoid_tools: list[NonEmptyStr] = Field(
        default_factory=list,
        description="Tools that should be avoided during retry.",
    )
    extra_constraints: list[NonEmptyStr] = Field(
        default_factory=list,
        description="Additional constraints to enforce during retry.",
    )
    parameter_adjustments: dict[str, Any] = Field(
        default_factory=dict,
        description="Low-level tool or model parameter overrides for retry.",
    )
    created_at: datetime = Field(default_factory=utc_now, description="UTC timestamp when the advice was created.")


class ReplanContext(StrictSchema):
    """Strategic escalation packet sent back to the planner."""

    replan_id: Identifier = Field(description="Unique identifier for this replan context.")
    failed_node_id: Identifier = Field(description="Node whose repeated failure triggered replanning.")
    source_evaluation_id: Identifier = Field(description="Evaluation result that triggered this replan context.")
    attempt_count: PositiveInt = Field(description="Number of failed attempts observed before escalation.")
    failure_type: FailureType = Field(description="Primary failure category behind the escalation.")
    reason: NonEmptyStr = Field(description="Human-readable explanation for replanning.")
    scope: ReplanScope = Field(description="How much of the workflow should be recomputed.")
    blocked_node_ids: list[Identifier] = Field(
        default_factory=list,
        description="Downstream nodes currently blocked by this failure.",
    )
    evidence_ids: list[Identifier] = Field(
        default_factory=list,
        description="Artifact or log ids supporting the replan decision.",
    )
    context_snapshot: NonEmptyStr = Field(description="Compact semantic snapshot of the failure context.")
    created_at: datetime = Field(default_factory=utc_now, description="UTC timestamp when the replan context was created.")


class ExecutionRequest(StrictSchema):
    """Standard task packet sent from the orchestrator to the executor."""

    workflow_id: Identifier = Field(description="Workflow requesting this execution.")
    plan_id: Identifier = Field(description="Plan that owns the node being executed.")
    plan_version: PositiveInt = Field(description="Numeric version of the active plan.")
    node_id: Identifier = Field(description="Node being executed.")
    node_kind: NodeKind = Field(description="Canonical task kind used as an execution prior.")
    attempt_id: Identifier = Field(description="Unique identifier of the concrete attempt.")
    objective: NonEmptyStr = Field(description="Task objective the executor should accomplish.")
    inputs: list[ArtifactBinding] = Field(default_factory=list, description="Concrete input bindings for this attempt.")
    output_slots: list[SlotSpec] = Field(
        default_factory=list,
        description="Declared final output slots this node may bind during execution.",
    )
    success: SuccessCriteria = Field(description="Acceptance criteria the executor should optimize toward.")
    allowed_tools: list[NonEmptyStr] = Field(
        default_factory=list,
        description="Tool names permitted during this execution.",
    )
    retry_from_attempt_id: Identifier | None = Field(
        default=None,
        description="Previous attempt id when this request is a retry.",
    )
    retry_advice: RetryAdvice | None = Field(
        default=None,
        description="Structured guidance carried over from the previous failed attempt.",
    )

    @model_validator(mode="after")
    def validate_request(self) -> "ExecutionRequest":
        if len(self.allowed_tools) != len(set(self.allowed_tools)):
            raise ValueError("allowed_tools must be unique")
        output_names = [slot.name for slot in self.output_slots]
        if len(output_names) != len(set(output_names)):
            raise ValueError("output slot names must be unique within an execution request")
        missing_required_outputs = sorted(set(self.success.required_outputs).difference(output_names))
        if missing_required_outputs:
            raise ValueError(
                "success.required_outputs contains undefined execution output slots: "
                + ", ".join(missing_required_outputs)
            )
        if self.retry_advice is not None and self.retry_from_attempt_id is None:
            raise ValueError("retry_from_attempt_id is required when retry_advice is provided")
        return self


class ActionStep(StrictSchema):
    """Single ReAct step captured during execution."""

    step_index: PositiveInt = Field(description="1-based index of this step inside the attempt.")
    thought: NonEmptyStr = Field(description="Reasoning that motivated the chosen tool action.")
    tool_name: NonEmptyStr = Field(description="Name of the tool invoked at this step.")
    tool_args: dict[str, Any] = Field(default_factory=dict, description="Arguments passed to the tool.")
    observation: NonEmptyStr = Field(description="Normalized observation returned from the tool.")
    started_at: datetime = Field(default_factory=utc_now, description="UTC timestamp when the step started.")
    finished_at: datetime = Field(default_factory=utc_now, description="UTC timestamp when the step finished.")

    @model_validator(mode="after")
    def validate_timing(self) -> "ActionStep":
        if self.finished_at < self.started_at:
            raise ValueError("finished_at cannot be earlier than started_at")
        return self


class ExecutionLog(StrictSchema):
    """Primary evidence record consumed by the evaluator."""

    execution_log_id: Identifier = Field(description="Unique identifier of this execution log.")
    workflow_id: Identifier = Field(description="Workflow associated with this execution log.")
    plan_id: Identifier = Field(description="Plan associated with this execution log.")
    plan_version: PositiveInt = Field(description="Numeric version of the active plan.")
    node_id: Identifier = Field(description="Node that was executed.")
    attempt_id: Identifier = Field(description="Attempt represented by this log.")
    status: AttemptStatus = Field(description="Lifecycle status of the attempt.")
    steps: list[ActionStep] = Field(default_factory=list, description="Ordered ReAct trace of the attempt.")
    outputs: list[ArtifactBinding] = Field(default_factory=list, description="Artifacts produced by this attempt, bound to output slots.")
    final_summary: str | None = Field(default=None, description="Optional executor summary of the attempt outcome.")
    started_at: datetime = Field(default_factory=utc_now, description="UTC timestamp when the attempt started.")
    finished_at: datetime | None = Field(default=None, description="UTC timestamp when the attempt finished.")

    @model_validator(mode="after")
    def validate_log(self) -> "ExecutionLog":
        indices = [step.step_index for step in self.steps]
        if len(indices) != len(set(indices)):
            raise ValueError("step_index values must be unique within an execution log")
        if indices and indices != sorted(indices):
            raise ValueError("steps must be sorted by ascending step_index")
        if self.finished_at is not None and self.finished_at < self.started_at:
            raise ValueError("finished_at cannot be earlier than started_at")
        return self


class EvaluationResult(StrictSchema):
    """Unified evaluator verdict that directly drives orchestrator routing."""

    evaluation_id: Identifier = Field(description="Unique identifier of this evaluation result.")
    execution_log_id: Identifier = Field(description="Execution log used as evaluator evidence.")
    decision: EvaluationDecision = Field(description="Next action chosen by the evaluator.")
    status: EvaluationStatus = Field(description="Binary pass/fail evaluation status.")
    failure_type: FailureType | None = Field(
        default=None,
        description="Failure category when the evaluation does not pass.",
    )
    retryable: bool = Field(default=False, description="Whether local retry is still valid.")
    scores: list[NamedScore] = Field(
        default_factory=list,
        description="Named quality scores normalized to [0,1], represented as a list for LLM compatibility.",
    )
    hard_rule_results: list[HardRuleResult] = Field(
        default_factory=list,
        description="Per-rule boolean results for hard acceptance rules.",
    )
    summary: NonEmptyStr = Field(description="Short evaluator summary.")
    advice: RetryAdvice | None = Field(default=None, description="Retry advice when the decision is RETRY.")
    replan: ReplanContext | None = Field(default=None, description="Replan context when the decision is REPLAN.")
    created_at: datetime = Field(default_factory=utc_now, description="UTC timestamp when the evaluation was created.")

    @model_validator(mode="after")
    def validate_evaluation(self) -> "EvaluationResult":
        score_names = [score.name for score in self.scores]
        if len(score_names) != len(set(score_names)):
            raise ValueError("score names must be unique within an evaluation result")
        hard_rules = [result.rule for result in self.hard_rule_results]
        if len(hard_rules) != len(set(hard_rules)):
            raise ValueError("hard rule names must be unique within an evaluation result")

        if self.status == EvaluationStatus.PASSED:
            if self.decision != EvaluationDecision.ACCEPT:
                raise ValueError("passed evaluations must use decision='accept'")
            if self.failure_type is not None:
                raise ValueError("failure_type must be omitted for passed evaluations")
            if self.retryable:
                raise ValueError("passed evaluations cannot be marked retryable")
            if self.advice is not None or self.replan is not None:
                raise ValueError("passed evaluations cannot include retry or replan payloads")
        else:
            if self.decision == EvaluationDecision.ACCEPT:
                raise ValueError("failed evaluations cannot use decision='accept'")
            if self.failure_type is None:
                raise ValueError("failure_type is required for failed evaluations")
            if self.decision == EvaluationDecision.RETRY:
                if not self.retryable:
                    raise ValueError("retry decisions must set retryable=True")
                if self.advice is None:
                    raise ValueError("retry decisions require advice")
                if self.replan is not None:
                    raise ValueError("retry decisions cannot include replan payload")
            elif self.decision == EvaluationDecision.REPLAN:
                if self.replan is None:
                    raise ValueError("replan decisions require replan payload")
                if self.advice is not None:
                    raise ValueError("replan decisions cannot include retry advice")
            elif self.decision == EvaluationDecision.ABORT:
                if self.advice is not None or self.replan is not None:
                    raise ValueError("abort decisions cannot include retry or replan payloads")
        return self


__all__ = [
    "ActionStep",
    "ArtifactBinding",
    "EvaluationResult",
    "ExecutionLog",
    "ExecutionRequest",
    "HardRuleResult",
    "NamedScore",
    "ReplanContext",
    "RetryAdvice",
]
